<?php
/**
 * Realex_Redirect extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Realex
 * @package    Realex_Redirect
 * @copyright  Copyright (c) 2015 StudioForty9
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<fieldset class="form-list">
    <?php $_code = $this->getMethodCode() ?>

    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li><?php echo $this->getCheckoutMessage(); ?></li>
        <?php if (Mage::getStoreConfig('payment/realex_redirect/amexAccount')): ?>
            <li>
                <input id="<?php echo $_code ?>_amex" value="amex" type="radio" name="payment[amex]"
                       title="<?php echo $this->__('American Express') ?>" class="radio"/>
                <label for="<?php echo $_code ?>_amex"><?php echo $this->__('Pay with American Express') ?></label><br/>
                <input id="<?php echo $_code ?>_other" value="other" type="radio" name="payment[amex]"
                       title="<?php echo $this->__('Other Credit Card') ?>" class="radio" checked="checked"/>
                <label
                    for="<?php echo $_code ?>_other"><?php echo $this->__('Pay with Other Credit/Debit Card') ?></label>
            </li>
        <?php endif; ?>
    </ul>
</fieldset>